### PR TITLE
Reroll a card

### LINKED ISSUE #33: Ability to reroll a card
Allow freely to reroll/redraw their current card

### PR DESCRIPTION
**Pull request by viirret**
Ability to reroll any card at any given moment and then the game continues normally.

- New function `loadSingleCard` that draws a new card with same seed for all languages and updates the `languageData`.
- New helper function `getCardUrl`
- New locale "reroll"
- Small UI changes

Closes #33

### CODE REVIEW

**Review by jervw — CHANGES_REQUESTED** [review]
Everything seems to work as intended. However, I am not really a fan of the design style that adds another button below another. I had an vision that the reroll button would be subtle and unnoticeable, possibly an icon at the top-right or bottom-right of the actual card. The icon could be the same as used to restart or even a dice. Let me know what you think. I can handle the styling if you are not bothered.

**Comment by viirret** [comment]
@jervw Sounds good.

**Comment by jervw** [comment]
Added styling. One caveat I discovered about rerolling: when you reroll the card and then refresh the page, the old card before redraw loads instead. Is this intended or not?

**Review by jervw — APPROVED** [review]
LGTM 🚀

**Pull request merged**
